import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATABASE_PATH = Path(os.getenv("DATABASE_PATH", ROOT / "data" / "video_rag.db"))
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
EMBEDDING_PROVIDER = os.getenv("EMBEDDING_PROVIDER", "mock").lower()
CHAT_PROVIDER = os.getenv("CHAT_PROVIDER", "mock").lower()
CLOVASTUDIO_API_KEY = os.getenv("CLOVASTUDIO_API_KEY")
CLOVA_MODEL = os.getenv("CLOVA_MODEL", "HCX-DASH-002")
CLOVA_SPEECH_INVOKE_URL = os.getenv("CLOVA_SPEECH_INVOKE_URL")
CLOVA_SPEECH_API_KEY = os.getenv("CLOVA_SPEECH_API_KEY")
CLOVA_SPEECH_LANGUAGE = os.getenv("CLOVA_SPEECH_LANGUAGE", "ko-KR")
NCP_OBJECT_STORAGE_ENDPOINT = os.getenv("NCP_OBJECT_STORAGE_ENDPOINT", "").rstrip("/")
NCP_OBJECT_STORAGE_REGION = os.getenv("NCP_OBJECT_STORAGE_REGION", "kr-standard")
NCP_OBJECT_STORAGE_BUCKET = os.getenv("NCP_OBJECT_STORAGE_BUCKET", "")
NCP_OBJECT_STORAGE_ACCESS_KEY = os.getenv("NCP_OBJECT_STORAGE_ACCESS_KEY", "")
NCP_OBJECT_STORAGE_SECRET_KEY = os.getenv("NCP_OBJECT_STORAGE_SECRET_KEY", "")
OBJECT_STORAGE_ARTIFACT_PREFIX = os.getenv("OBJECT_STORAGE_ARTIFACT_PREFIX", "videos").strip("/")
OBJECT_STORAGE_STT_INPUT_PREFIX = os.getenv("OBJECT_STORAGE_STT_INPUT_PREFIX", "clova-speech/input").strip("/")
OBJECT_STORAGE_STT_RESULT_PREFIX = os.getenv("OBJECT_STORAGE_STT_RESULT_PREFIX", "clova-speech/result").strip("/")
YTDLP_BIN = os.getenv("YTDLP_BIN", "yt-dlp")
WORKER_RAG_CHUNK_MAX_SECONDS = float(os.getenv("WORKER_RAG_CHUNK_MAX_SECONDS", "60"))
WORKER_RAG_CHUNK_MAX_CHARS = int(os.getenv("WORKER_RAG_CHUNK_MAX_CHARS", "1600"))
WORKER_EMBEDDING_MIN_INTERVAL_SECONDS = float(os.getenv("WORKER_EMBEDDING_MIN_INTERVAL_SECONDS", "1.5"))
WORKER_EMBEDDING_MAX_RETRIES = int(os.getenv("WORKER_EMBEDDING_MAX_RETRIES", "5"))
WORKER_EMBEDDING_BACKOFF_BASE_SECONDS = float(os.getenv("WORKER_EMBEDDING_BACKOFF_BASE_SECONDS", "2"))
DATA_DIR = DATABASE_PATH.parent
SESSION_COOKIE_NAME = "video_rag_session"
SESSION_MAX_AGE_SECONDS = int(os.getenv("SESSION_MAX_AGE_SECONDS", str(60 * 60 * 24 * 30)))
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").lower() == "true"
SESSION_COOKIE_DOMAIN = os.getenv("SESSION_COOKIE_DOMAIN") or None
CORS_ALLOW_ORIGINS = tuple(
    origin.strip() for origin in os.getenv("CORS_ALLOW_ORIGINS", "").split(",") if origin.strip()
)
CHAT_PUBLIC_ORIGIN = os.getenv("CHAT_PUBLIC_ORIGIN", "").rstrip("/")
