import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

ROOT = Path(__file__).resolve().parents[1]
DATABASE_PATH = Path(os.getenv("DATABASE_PATH", ROOT / "data" / "video_rag.db"))
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
EMBEDDING_PROVIDER = os.getenv("EMBEDDING_PROVIDER", "mock").lower()
CHAT_PROVIDER = os.getenv("CHAT_PROVIDER", "mock").lower()
CLOVASTUDIO_API_KEY = os.getenv("CLOVASTUDIO_API_KEY")
CLOVA_MODEL = os.getenv("CLOVA_MODEL", "HCX-DASH-002")
CHAT_HISTORY_TURNS = int(os.getenv("CHAT_HISTORY_TURNS", "3"))
REDIS_URL = os.getenv("REDIS_URL", "").strip()
REDIS_CHAT_CACHE_TTL_SECONDS = int(os.getenv("REDIS_CHAT_CACHE_TTL_SECONDS", str(60 * 60)))
REDIS_LOCK_TTL_SECONDS = int(os.getenv("REDIS_LOCK_TTL_SECONDS", "300"))
REDIS_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("REDIS_RATE_LIMIT_WINDOW_SECONDS", "60"))
REDIS_IMPORT_RATE_LIMIT = int(os.getenv("REDIS_IMPORT_RATE_LIMIT", "30"))
CLOVA_SPEECH_INVOKE_URL = os.getenv("CLOVA_SPEECH_INVOKE_URL")
CLOVA_SPEECH_API_KEY = os.getenv("CLOVA_SPEECH_API_KEY")
CLOVA_SPEECH_LANGUAGE = os.getenv("CLOVA_SPEECH_LANGUAGE", "ko-KR")
NCP_OBJECT_STORAGE_ENDPOINT = os.getenv("NCP_OBJECT_STORAGE_ENDPOINT", "").rstrip("/")
NCP_OBJECT_STORAGE_REGION = os.getenv("NCP_OBJECT_STORAGE_REGION", "kr-standard")
NCP_OBJECT_STORAGE_BUCKET = os.getenv("NCP_OBJECT_STORAGE_BUCKET", "")
NCP_OBJECT_STORAGE_ACCESS_KEY = os.getenv("NCP_OBJECT_STORAGE_ACCESS_KEY", "")
NCP_OBJECT_STORAGE_SECRET_KEY = os.getenv("NCP_OBJECT_STORAGE_SECRET_KEY", "")
OBJECT_STORAGE_ARTIFACT_PREFIX = os.getenv("OBJECT_STORAGE_ARTIFACT_PREFIX", "videos").strip("/")
OBJECT_STORAGE_IMPORT_PREFIX = os.getenv("OBJECT_STORAGE_IMPORT_PREFIX", "imports").strip("/")
OBJECT_STORAGE_STT_INPUT_PREFIX = os.getenv("OBJECT_STORAGE_STT_INPUT_PREFIX", "clova-speech/input").strip("/")
OBJECT_STORAGE_STT_RESULT_PREFIX = os.getenv("OBJECT_STORAGE_STT_RESULT_PREFIX", "clova-speech/result").strip("/")
YTDLP_BIN = os.getenv("YTDLP_BIN", "yt-dlp")
YTDLP_SLEEP_REQUESTS_SECONDS = float(os.getenv("YTDLP_SLEEP_REQUESTS_SECONDS", "5"))
YTDLP_SLEEP_INTERVAL_SECONDS = float(os.getenv("YTDLP_SLEEP_INTERVAL_SECONDS", "5"))
YTDLP_MAX_SLEEP_INTERVAL_SECONDS = float(os.getenv("YTDLP_MAX_SLEEP_INTERVAL_SECONDS", "10"))
YTDLP_RATE_LIMIT_RETRY_DELAY_SECONDS = int(os.getenv("YTDLP_RATE_LIMIT_RETRY_DELAY_SECONDS", str(60 * 60)))
ANALYSIS_QUEUE_PROVIDER = os.getenv("ANALYSIS_QUEUE_PROVIDER", "postgres").strip().lower()
RABBITMQ_URL = os.getenv("RABBITMQ_URL", "").strip()
RABBITMQ_QUEUE = os.getenv("RABBITMQ_QUEUE", "analysis.jobs").strip()
RABBITMQ_PRIORITY_MAX = int(os.getenv("RABBITMQ_PRIORITY_MAX", "10"))
WORKER_QUEUE_MODE = os.getenv("WORKER_QUEUE_MODE", "postgres").strip().lower()
WORKER_PREFETCH_COUNT = int(os.getenv("WORKER_PREFETCH_COUNT", "1"))
WORKER_MAX_CONCURRENT_ANALYSIS = int(os.getenv("WORKER_MAX_CONCURRENT_ANALYSIS", "1"))
WORKER_OUTBOX_PUBLISH_INTERVAL_SECONDS = int(os.getenv("WORKER_OUTBOX_PUBLISH_INTERVAL_SECONDS", "30"))
PDF_FONT_PATH = os.getenv("PDF_FONT_PATH", "")
WORKER_PARAGRAPH_MAX_SECONDS = float(os.getenv("WORKER_PARAGRAPH_MAX_SECONDS", "75"))
WORKER_PARAGRAPH_MAX_CHARS = int(os.getenv("WORKER_PARAGRAPH_MAX_CHARS", "1800"))
WORKER_RAG_CHUNK_MAX_SECONDS = float(os.getenv("WORKER_RAG_CHUNK_MAX_SECONDS", "25"))
WORKER_RAG_CHUNK_MAX_CHARS = int(os.getenv("WORKER_RAG_CHUNK_MAX_CHARS", "700"))
WORKER_EMBEDDING_MIN_INTERVAL_SECONDS = float(os.getenv("WORKER_EMBEDDING_MIN_INTERVAL_SECONDS", "1.5"))
WORKER_EMBEDDING_MAX_RETRIES = int(os.getenv("WORKER_EMBEDDING_MAX_RETRIES", "5"))
WORKER_EMBEDDING_BACKOFF_BASE_SECONDS = float(os.getenv("WORKER_EMBEDDING_BACKOFF_BASE_SECONDS", "2"))
DATA_DIR = DATABASE_PATH.parent
SESSION_COOKIE_NAME = "video_rag_session"
SESSION_MAX_AGE_SECONDS = int(os.getenv("SESSION_MAX_AGE_SECONDS", str(60 * 60 * 24 * 30)))
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").lower() == "true"
SESSION_COOKIE_DOMAIN = os.getenv("SESSION_COOKIE_DOMAIN") or None
CORS_ALLOW_ORIGINS = tuple(
    origin.strip() for origin in os.getenv("CORS_ALLOW_ORIGINS", "").split(",") if origin.strip()
)
CHAT_PUBLIC_ORIGIN = os.getenv("CHAT_PUBLIC_ORIGIN", "").rstrip("/")

CLOVA_VOICE_CLIENT_ID = os.getenv("CLOVA_VOICE_CLIENT_ID", "")
CLOVA_VOICE_CLIENT_SECRET = os.getenv("CLOVA_VOICE_CLIENT_SECRET", "")
CLOVA_VOICE_URL = os.getenv(
    "CLOVA_VOICE_URL",
    "https://naveropenapi.apigw.ntruss.com/tts-premium/v1/tts",
)
REDIS_TTS_CACHE_TTL_SECONDS = int(os.getenv("REDIS_TTS_CACHE_TTL_SECONDS", str(60 * 60 * 24)))
