"""SQLite for local MVP, Cloud DB for PostgreSQL for separate NCP servers."""

import re
import sqlite3
from contextlib import contextmanager
from typing import Any

from .config import DATABASE_PATH, DATABASE_URL


SQLITE_SCHEMA = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    workspace_code TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    name TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_scanned_at TEXT,
    UNIQUE(user_id, url)
);

CREATE TABLE IF NOT EXISTS videos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    platform_video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    url TEXT NOT NULL,
    thumbnail_url TEXT,
    duration_seconds INTEGER,
    uploaded_at TEXT,
    metadata_embedding TEXT,
    analysis_status TEXT NOT NULL DEFAULT 'metadata_only',
    analysis_stage TEXT NOT NULL DEFAULT 'metadata_only',
    analysis_message TEXT,
    analysis_error TEXT,
    analysis_updated_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analyzed_at TEXT,
    UNIQUE(channel_id, platform_video_id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL CHECK(kind IN ('scan_channel', 'analyze_video')),
    resource_id INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued', 'running', 'succeeded', 'failed')),
    progress_stage TEXT NOT NULL DEFAULT 'queued',
    progress_message TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    started_at TEXT,
    finished_at TEXT
);

CREATE TABLE IF NOT EXISTS transcript_paragraphs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    paragraph_index INTEGER NOT NULL,
    start_seconds REAL NOT NULL,
    end_seconds REAL NOT NULL,
    text TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(video_id, paragraph_index)
);

CREATE TABLE IF NOT EXISTS transcript_chunks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    paragraph_id INTEGER REFERENCES transcript_paragraphs(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    start_seconds REAL NOT NULL,
    end_seconds REAL NOT NULL,
    text TEXT NOT NULL,
    embedding TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_artifacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    object_key TEXT NOT NULL,
    content_type TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(job_id, kind)
);

CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    video_id INTEGER REFERENCES videos(id) ON DELETE SET NULL,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    evidence_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status, id);
CREATE INDEX IF NOT EXISTS idx_channels_user ON channels(user_id, id);
CREATE INDEX IF NOT EXISTS idx_videos_channel ON videos(channel_id);
CREATE INDEX IF NOT EXISTS idx_chunks_video ON transcript_chunks(video_id);
CREATE INDEX IF NOT EXISTS idx_transcript_paragraphs_video ON transcript_paragraphs(video_id, paragraph_index);
CREATE INDEX IF NOT EXISTS idx_analysis_artifacts_video ON analysis_artifacts(video_id, id);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user ON chat_messages(user_id, id);
"""


POSTGRES_SCHEMA = """
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_scanned_at TIMESTAMPTZ,
    UNIQUE(user_id, url)
);

CREATE TABLE IF NOT EXISTS videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    platform_video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    url TEXT NOT NULL,
    thumbnail_url TEXT,
    duration_seconds INTEGER,
    uploaded_at TEXT,
    metadata_embedding vector(1024),
    analysis_status TEXT NOT NULL DEFAULT 'metadata_only',
    analysis_stage TEXT NOT NULL DEFAULT 'metadata_only',
    analysis_message TEXT,
    analysis_error TEXT,
    analysis_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analyzed_at TIMESTAMPTZ,
    UNIQUE(channel_id, platform_video_id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK(kind IN ('scan_channel', 'analyze_video')),
    resource_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued', 'running', 'succeeded', 'failed')),
    progress_stage TEXT NOT NULL DEFAULT 'queued',
    progress_message TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS transcript_paragraphs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    paragraph_index INTEGER NOT NULL,
    start_seconds DOUBLE PRECISION NOT NULL,
    end_seconds DOUBLE PRECISION NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(video_id, paragraph_index)
);

CREATE TABLE IF NOT EXISTS transcript_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    paragraph_id BIGINT REFERENCES transcript_paragraphs(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    start_seconds DOUBLE PRECISION NOT NULL,
    end_seconds DOUBLE PRECISION NOT NULL,
    text TEXT NOT NULL,
    embedding vector(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    object_key TEXT NOT NULL,
    content_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(job_id, kind)
);

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    evidence_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status, id);
CREATE INDEX IF NOT EXISTS idx_channels_user ON channels(user_id, id);
CREATE INDEX IF NOT EXISTS idx_videos_channel ON videos(channel_id);
CREATE INDEX IF NOT EXISTS idx_chunks_video ON transcript_chunks(video_id);
CREATE INDEX IF NOT EXISTS idx_transcript_paragraphs_video ON transcript_paragraphs(video_id, paragraph_index);
CREATE INDEX IF NOT EXISTS idx_analysis_artifacts_video ON analysis_artifacts(video_id, id);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user ON chat_messages(user_id, id);
CREATE INDEX IF NOT EXISTS idx_chunks_embedding_hnsw
    ON transcript_chunks USING hnsw (embedding vector_cosine_ops);
"""

SQLITE_NOW = "strftime('%Y-%m-%dT%H:%M:%fZ', 'now')"
# PostgreSQL timestamp columns must receive a timestamp, not a formatted string.
# SSE converts psycopg datetime values to ISO-8601 only when building its response.
POSTGRES_NOW = "CURRENT_TIMESTAMP"


def is_postgres() -> bool:
    return bool(DATABASE_URL)


def _postgres_sql(sql: str) -> str:
    sql = sql.replace(SQLITE_NOW, POSTGRES_NOW)
    return re.sub(r"\?", "%s", sql)


class PostgresConnection:
    """Keeps existing qmark SQL calls working on psycopg without duplicating services."""

    def __init__(self, raw: Any):
        self.raw = raw

    def execute(self, sql: str, params: Any = None):
        return self.raw.execute(_postgres_sql(sql), params or ())

    def executescript(self, script: str) -> None:
        for statement in script.split(";"):
            if statement.strip():
                self.raw.execute(statement)


@contextmanager
def connection():
    if not is_postgres():
        DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(DATABASE_PATH))
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()
        return

    import psycopg
    from psycopg.rows import dict_row

    raw = psycopg.connect(DATABASE_URL, row_factory=dict_row)
    conn = PostgresConnection(raw)
    try:
        yield conn
        raw.commit()
    except Exception:
        raw.rollback()
        raise
    finally:
        raw.close()


def initialize():
    if is_postgres():
        with connection() as conn:
            # API, Chat, and Worker can start together; serialize schema creation.
            conn.execute("SELECT pg_advisory_xact_lock(7401024)")
            conn.executescript(POSTGRES_SCHEMA)
            conn.execute("ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS evidence_json TEXT")
            conn.execute("ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL")
            conn.execute("ALTER TABLE transcript_chunks ADD COLUMN IF NOT EXISTS paragraph_id BIGINT")
            conn.execute("ALTER TABLE transcript_chunks ADD COLUMN IF NOT EXISTS chunk_index INTEGER NOT NULL DEFAULT 0")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_chat_messages_user_video ON chat_messages(user_id, video_id, id)")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_chunks_paragraph ON transcript_chunks(paragraph_id, chunk_index)")
        return

    with connection() as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                workspace_code TEXT NOT NULL UNIQUE,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS sessions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                expires_at TEXT NOT NULL,
                last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """
        )
        columns = {row["name"] for row in conn.execute("PRAGMA table_info(channels)")}
        channel_schema = conn.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='channels'"
        ).fetchone()
        workspace_unique = channel_schema and "UNIQUE(user_id, url)" in channel_schema["sql"]
        channel_count = conn.execute("SELECT COUNT(*) AS count FROM channels").fetchone()["count"] if columns else 0
        video_count = conn.execute("SELECT COUNT(*) AS count FROM videos").fetchone()["count"] if columns else 0
        if columns and not workspace_unique and channel_count == 0 and video_count == 0:
            conn.execute("DROP TABLE channels")
            columns = set()
        if columns and "user_id" not in columns:
            conn.execute("ALTER TABLE channels ADD COLUMN user_id INTEGER REFERENCES users(id)")
        conn.executescript(SQLITE_SCHEMA)
        _add_column_if_missing(conn, "videos", "analysis_stage", "TEXT")
        _add_column_if_missing(conn, "videos", "analysis_message", "TEXT")
        _add_column_if_missing(conn, "videos", "analysis_updated_at", "TEXT")
        _add_column_if_missing(conn, "jobs", "progress_stage", "TEXT")
        _add_column_if_missing(conn, "jobs", "progress_message", "TEXT")
        _add_column_if_missing(conn, "jobs", "updated_at", "TEXT")
        _add_column_if_missing(conn, "chat_messages", "evidence_json", "TEXT")
        _add_column_if_missing(conn, "chat_messages", "video_id", "INTEGER REFERENCES videos(id) ON DELETE SET NULL")
        _add_column_if_missing(conn, "transcript_chunks", "paragraph_id", "INTEGER")
        _add_column_if_missing(conn, "transcript_chunks", "chunk_index", "INTEGER NOT NULL DEFAULT 0")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_chat_messages_user_video ON chat_messages(user_id, video_id, id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_chunks_paragraph ON transcript_chunks(paragraph_id, chunk_index)")
        conn.execute("UPDATE videos SET analysis_status='succeeded' WHERE analysis_status='ready'")
        conn.execute(
            """
            UPDATE videos
            SET analysis_stage=COALESCE(
                    analysis_stage,
                    CASE analysis_status
                        WHEN 'succeeded' THEN 'completed'
                        WHEN 'failed' THEN 'failed'
                        WHEN 'running' THEN 'downloading_caption'
                        WHEN 'queued' THEN 'queued'
                        ELSE 'metadata_only'
                    END
                ),
                analysis_updated_at=COALESCE(analysis_updated_at, analyzed_at, created_at)
            """
        )
        conn.execute(
            """
            UPDATE jobs
            SET progress_stage=COALESCE(
                    progress_stage,
                    CASE status
                        WHEN 'succeeded' THEN 'completed'
                        WHEN 'failed' THEN 'failed'
                        WHEN 'running' THEN 'downloading_caption'
                        ELSE 'queued'
                    END
                ),
                updated_at=COALESCE(updated_at, finished_at, started_at, created_at)
            """
        )


def _add_column_if_missing(conn, table: str, column: str, definition: str):
    columns = {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}
    if column not in columns:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def is_unique_violation(exc: Exception) -> bool:
    return "unique constraint failed" in str(exc).lower() or "duplicate key" in str(exc).lower()
