-- Folder-first Video RAG schema migration for deployed PostgreSQL.
-- Safe to run more than once. It only creates missing tables, columns, and indexes.

BEGIN;

CREATE TABLE IF NOT EXISTS folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    UNIQUE(user_id, name)
);

ALTER TABLE channels
    ADD COLUMN IF NOT EXISTS folder_id BIGINT REFERENCES folders(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS folder_videos (
    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
    video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    source TEXT NOT NULL DEFAULT 'manual',
    position INTEGER,
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(folder_id, video_id)
);

ALTER TABLE chat_messages
    ADD COLUMN IF NOT EXISTS folder_id BIGINT REFERENCES folders(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_folders_user
    ON folders(user_id, id);

CREATE INDEX IF NOT EXISTS idx_channels_folder
    ON channels(folder_id, id);

CREATE INDEX IF NOT EXISTS idx_folder_videos_folder
    ON folder_videos(folder_id, position, added_at);

CREATE INDEX IF NOT EXISTS idx_folder_videos_video
    ON folder_videos(video_id);

CREATE INDEX IF NOT EXISTS idx_chat_messages_user_folder
    ON chat_messages(user_id, folder_id, id);

COMMIT;
