-- KakaoTalk YouTube import + priority analysis queue.
-- Apply before increasing Worker replicas in production.

BEGIN;

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 100;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS payload_json TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 3;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS next_run_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS locked_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS locked_by TEXT;

ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_kind_check;
ALTER TABLE jobs ADD CONSTRAINT jobs_kind_check
    CHECK(kind IN ('scan_channel', 'analyze_video', 'ingest_video'));

CREATE TABLE IF NOT EXISTS video_analysis_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_video_id TEXT NOT NULL,
    canonical_url TEXT NOT NULL,
    representative_video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL,
    analysis_status TEXT NOT NULL DEFAULT 'metadata_only',
    last_job_id BIGINT REFERENCES jobs(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    UNIQUE(provider, provider_video_id)
);

CREATE TABLE IF NOT EXISTS import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
    source_kind TEXT NOT NULL DEFAULT 'kakao',
    filename TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    artifact_object_key TEXT,
    total_urls INTEGER NOT NULL DEFAULT 0,
    unique_videos INTEGER NOT NULL DEFAULT 0,
    duplicates INTEGER NOT NULL DEFAULT 0,
    queued_jobs INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'completed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
    folder_id BIGINT NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
    video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL,
    job_id BIGINT REFERENCES jobs(id) ON DELETE SET NULL,
    provider TEXT NOT NULL,
    provider_video_id TEXT NOT NULL,
    source_url TEXT NOT NULL,
    canonical_url TEXT NOT NULL,
    start_seconds_hint INTEGER,
    status TEXT NOT NULL,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    aggregate_type TEXT NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_jobs_status_priority ON jobs(status, priority, id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_jobs_active_idempotency
    ON jobs(idempotency_key)
    WHERE idempotency_key IS NOT NULL AND status IN ('queued', 'running');
CREATE INDEX IF NOT EXISTS idx_video_analysis_index_identity
    ON video_analysis_index(provider, provider_video_id);
CREATE INDEX IF NOT EXISTS idx_import_batches_user_folder
    ON import_batches(user_id, folder_id, id);
CREATE INDEX IF NOT EXISTS idx_import_items_batch
    ON import_items(batch_id, id);
CREATE INDEX IF NOT EXISTS idx_outbox_events_status
    ON outbox_events(status, id);

COMMIT;
